# Generated by Django 3.1.7 on 2025-03-09 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailydata',
            old_name='btc_commentsPerHour',
            new_name='btc_comments_per_hour',
        ),
        migrations.RenameField(
            model_name='dailydata',
            old_name='btc_postsPerHour',
            new_name='btc_posts_per_hour',
        ),
        migrations.RenameField(
            model_name='dailydata',
            old_name='btc_subscriberCount',
            new_name='btc_subscriber_count',
        ),
        migrations.RenameField(
            model_name='dailydata',
            old_name='crypto_commentsPerHour',
            new_name='crypto_comments_per_hour',
        ),
        migrations.RenameField(
            model_name='dailydata',
            old_name='crypto_postsPerHour',
            new_name='crypto_posts_per_hour',
        ),
        migrations.RenameField(
            model_name='dailydata',
            old_name='crypto_subscriberCount',
            new_name='crypto_subscriber_count',
        ),
        migrations.RenameField(
            model_name='dailydata',
            old_name='xmr_commentsPerHour',
            new_name='xmr_comments_per_hour',
        ),
        migrations.RenameField(
            model_name='dailydata',
            old_name='xmr_postsPerHour',
            new_name='xmr_posts_per_hour',
        ),
        migrations.RenameField(
            model_name='dailydata',
            old_name='xmr_subscriberCount',
            new_name='xmr_subscriber_count',
        ),
        migrations.RenameField(
            model_name='social',
            old_name='commentsPerHour',
            new_name='comments_per_hour',
        ),
        migrations.RenameField(
            model_name='social',
            old_name='postsPerHour',
            new_name='posts_per_hour',
        ),
        migrations.RenameField(
            model_name='social',
            old_name='subscriberCount',
            new_name='subscriber_count',
        ),
    ]
