# Generated by Django 3.1.7 on 2025-04-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_auto_20250309_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('bitcoin_pct', models.FloatField(default=0)),
                ('monero_pct', models.FloatField(default=0)),
                ('ethereum_pct', models.FloatField(default=0)),
                ('others_pct', models.FloatField(default=0)),
                ('data_source', models.CharField(default='coincards', max_length=32)),
            ],
        ),
    ]
