# Generated by Django 3.1.7 on 2025-05-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('merchants_accepting_bitcoin', models.IntegerField(default=0)),
                ('merchants_accepting_ethereum', models.IntegerField(default=0)),
                ('merchants_accepting_bitcoincash', models.IntegerField(default=0)),
                ('merchants_accepting_litecoin', models.IntegerField(default=0)),
                ('merchants_accepting_ripple', models.IntegerField(default=0)),
                ('merchants_accepting_dash', models.IntegerField(default=0)),
                ('merchants_accepting_monero', models.IntegerField(default=0)),
                ('data_source', models.CharField(default='acceptedhere', max_length=32)),
            ],
        ),
    ]
