# Generated by Django 3.1.7 on 2025-05-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_adoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bitcoin_subscriber_count', models.IntegerField()),
                ('monero_subscriber_count', models.IntegerField()),
            ],
        ),
    ]
