# Generated by Django 3.1.7 on 2025-05-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0005_dread'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('monero_private_transactions', models.IntegerField(default=0)),
                ('zcash_shielded_transactions', models.IntegerField(default=0)),
                ('bitcoin_whirpool_transactions', models.IntegerField(default=0)),
            ],
        ),
    ]
