# Generated by Django 3.1.7 on 2025-05-27 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0006_transactions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
    ]
