# Generated by Django 3.1.7 on 2025-05-27 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0007_auto_20250527_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='monero_private_transactions',
        ),
    ]
