# Generated by Django 3.1.7 on 2025-06-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0008_remove_transaction_monero_private_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='name',
            field=models.CharField(max_length=16),
        ),
    ]
