# Generated by Django 3.1.7 on 2025-09-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0009_auto_20250628_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydata',
            name='bisq_num_trades',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailydata',
            name='bisq_volume',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dailydata',
            name='haveno_num_trades',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailydata',
            name='haveno_volume',
            field=models.FloatField(default=0),
        ),
    ]
