## Django with Static files by NGINX

name: moneroj

services:
  django:
    build:
      context: .
    volumes:
      - ./data:/opt
      - ./app:/src/app
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "gunicorn moneropro.wsgi:application --bind 0.0.0.0:8000 --timeout 300 --workers 2"
  nginx:
    image: nginx:1.27
    ports:
      - 8000:8000
    volumes:
      - ./app/static:/usr/share/nginx/html/static
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
