# Django with SQLite database and optional Celery worker

name: moneroj

services:
  django:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./data:/opt
      - ./app:/src/app
    entrypoint:
      - "bin/sh"
      - "-c"
      - "gunicorn moneropro.wsgi:application --bind 0.0.0.0:8000 --timeout 300 --workers 2"
#    depends_on:
#      - redis
#  celery:
#    build:
#      context: .
#    volumes:
#      - ./data:/opt
#      - ./app:/src/app
#    entrypoint:
#      - celery
#      - -A 
#      - tasks
#      - worker
#    depends_on:
#      - redis
#  redis:
#    image: redis:7
