from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [
    # Página inicial
    url(r'^$', views.index, name='index'),
    path('pricelog/', views.pricelog, name='pricelog'),
    path('movingaverage/', views.movingaverage, name='movingaverage'),
    path('pricelin/', views.pricelin, name='pricelin'),
    path('powerlaw/', views.powerlaw, name='powerlaw'),
    path('pricesats/', views.pricesats, name='pricesats'),
    path('fractal/', views.fractal, name='fractal'),
    path('golden/', views.golden, name='golden'),
    path('competitors/', views.competitors, name='competitors'),
    path('competitorssats/', views.competitorssats, name='competitorssats'),
    path('competitorssatslin/', views.competitorssatslin, name='competitorssatslin'),
    path('translin/', views.translin, name='translin'),
    path('percentage/', views.percentage, name='percentage'),
    path('translog/', views.translog, name='translog'),
    path('metcalfesats/', views.metcalfesats, name='metcalfesats'),
    path('metcalfeusd/', views.metcalfeusd, name='metcalfeusd'),
    path('coins/', views.coins, name='coins'),
    path('extracoins/', views.extracoins, name='extracoins'),
    path('inflation/', views.inflation, name='inflation'),
    path('compinflation/', views.compinflation, name='compinflation'),
    path('sfmodel/', views.sfmodel, name='sfmodel'),
    path('sfmodellin/', views.sfmodellin, name='sfmodellin'),
    path('sfmodel/', views.sfmodel, name='sfmodel'),
    path('sfmultiple/', views.sfmultiple, name='sfmultiple'),
    path('about/', views.about, name='about'),
    path('bitcoin/', views.bitcoin, name='bitcoin'),
    path('pt/', views.pt, name='pt'),
    path('fr/', views.fr, name='fr'),
    path('index_pt/', views.pt, name='index_pt'),
    path('thermocap/', views.thermocap, name='thermocap'),
    path('sharpe/', views.sharpe, name='sharpe'),
    path('social/', views.social, name='social'),
    path('social2/', views.social2, name='social2'),
    path('social3/', views.social3, name='social3'),
    path('social4/', views.social4, name='social4'),
    path('social5/', views.social5, name='social5'),
    path('social6/', views.social6, name='social6'),
    path('social7/', views.social7, name='social7'),
    path('hashrate/', views.hashrate, name='hashrate'),
    path('hashprice/', views.hashprice, name='hashprice'),
    path('hashvsprice/', views.hashvsprice, name='hashvsprice'),
    path('inflationfractal/', views.inflationfractal, name='inflationfractal'),
    path('dailyemission/', views.dailyemission, name='dailyemission'),
    path('dailyemissionntv/', views.dailyemissionntv, name='dailyemissionntv'),
    path('transcost/', views.transcost, name='transcost'),
    path('transcostntv/', views.transcostntv, name='transcostntv'),
    path('minerrevcap/', views.minerrevcap, name='minerrevcap'),
    path('minerrev/', views.minerrev, name='minerrev'),
    path('minerrevntv/', views.minerrevntv, name='minerrevntv'),
    path('minerfees/', views.minerfees, name='minerfees'),
    path('minerfeesntv/', views.minerfeesntv, name='minerfeesntv'),
    path('commit/', views.commit, name='commit'),
    path('commitntv/', views.commitntv, name='commitntv'),
    path('inflationreturn/', views.inflationreturn, name='inflationreturn'),
    path('dread_subscribers/', views.dread_subscribers, name='dread_subscribers'),
    path('coincards/', views.coincards, name='coincards'),
    path('merchants/', views.merchants, name='merchants'),
    path('merchants_increase/', views.merchants_increase, name='merchants_increase'),
    path('merchants_percentage/', views.merchants_percentage, name='merchants_percentage'),
    path('dominance/', views.dominance, name='dominance'),
    path('rank/', views.rank, name='rank'),
    path('marketcap/', views.marketcap, name='marketcap'),
    path('artigos/', views.artigos, name='artigos'),
    path('articles/', views.articles, name='articles'),

    # URLs to useful functions on monerojnet/views.py
    # Only admins can use these 
    path('get_history/<str:symbol>/<str:start_time>/<str:end_time>/', views.get_history, name='get_history'),
    path('get_complete_history/<str:symbol>/', views.get_history, name='get_complete_history'),
    path('load_dominance/<str:symbol>/', views.load_dominance, name='load_dominance'),
    path('load_rank/<str:symbol>/', views.load_rank, name='load_rank'),
    path('importer/', views.importer, name='importer'),
    path('reset/<str:symbol>/', views.reset, name='reset'),

]