from django.urls import path
from .views import main
from .views import authenticated

urlpatterns = [
    # Pages URLs
    # Everyone can use these
    path("", main.index, name="index"),
    path("pricelog/", main.pricelog, name="pricelog"),
    path("movingaverage/", main.movingaverage, name="movingaverage"),
    path("pricelin/", main.pricelin, name="pricelin"),
    path("powerlaw/", main.powerlaw, name="powerlaw"),
    path("fractal/", main.fractal, name="fractal"),
    path("golden/", main.golden, name="golden"),
    path("competitors/", main.competitors, name="competitors"),
    path("competitorslin/", main.competitorslin, name="competitorslin"),
    path("competitorssats/", main.competitorssats, name="competitorssats"),
    path("competitorssatslin/", main.competitorssatslin, name="competitorssatslin"),
    path("translin/", main.translin, name="translin"),
    path("translog/", main.translog, name="translog"),
    path("metcalfesats/", main.metcalfesats, name="metcalfesats"),
    path("metcalfeusd/", main.metcalfeusd, name="metcalfeusd"),
    path("inflation/", main.inflation, name="inflation"),
    path("coins/", main.coins, name="coins"),
    path("extracoins/", main.extracoins, name="extracoins"),
    path("sfmodel/", main.sfmodel, name="sfmodel"),
    path("sfmodellin/", main.sfmodellin, name="sfmodellin"),
    path("sfmultiple/", main.sfmultiple, name="sfmultiple"),
    path("about/", main.about, name="about"),
    path("compinflation/", main.compinflation, name="compinflation"),
    path("bitcoin/", main.bitcoin, name="bitcoin"),
    path("thermocap/", main.thermocap, name="thermocap"),
    path("sharpe/", main.sharpe, name="sharpe"),
    path("pricesats/", main.pricesats, name="pricesats"),
    path("social/", main.social, name="social"),
    path("social2/", main.social2, name="social2"),
    path("social3/", main.social3, name="social3"),
    path("social4/", main.social4, name="social4"),
    path("social5/", main.social5, name="social5"),
    path("social6/", main.social6, name="social6"),
    path("social7/", main.social7, name="social7"),
    path("hashrate/", main.hashrate, name="hashrate"),
    path("hashprice/", main.hashprice, name="hashprice"),
    path("hashvsprice/", main.hashvsprice, name="hashvsprice"),
    path("inflationfractal/", main.inflationfractal, name="inflationfractal"),
    path("dailyemission/", main.dailyemission, name="dailyemission"),
    path("dailyemissionntv/", main.dailyemissionntv, name="dailyemissionntv"),
    path("transcost/", main.transcost, name="transcost"),
    path("transcostntv/", main.transcostntv, name="transcostntv"),
    path("minerrevcap/", main.minerrevcap, name="minerrevcap"),
    path("minerrev/", main.minerrev, name="minerrev"),
    path("minerrevntv/", main.minerrevntv, name="minerrevntv"),
    path("minerfees/", main.minerfees, name="minerfees"),
    path("minerfeesntv/", main.minerfeesntv, name="minerfeesntv"),
    path("commit/", main.commit, name="commit"),
    path("commitntv/", main.commitntv, name="commitntv"),
    path("inflationreturn/", main.inflationreturn, name="inflationreturn"),
    path("dread_subscribers/", main.dread_subscribers, name="dread_subscribers"),
    path("marketcap/", main.marketcap, name="marketcap"),
    path("coincards/", main.coincards, name="coincards"),
    path("merchants/", main.merchants, name="merchants"),
    path("merchants_increase/", main.merchants_increase, name="merchants_increase"),
    path(
        "merchants_percentage/", main.merchants_percentage, name="merchants_percentage"
    ),
    path("dominance/", main.dominance, name="dominance"),
    path("rank/", main.rank, name="rank"),
    path("percentage/", main.percentage, name="percentage"),
    path("marketcap/", main.marketcap, name="marketcap"),
    path("tail_emission/", main.tail_emission, name="tail_emission"),
    path("privacymarketcap/", main.privacymarketcap, name="privacymarketcap"),
    path("privacydominance/", main.privacydominance, name="privacydominance"),
    path("monerodominance/", main.monerodominance, name="monerodominance"),
    path("blocksize/", main.blocksize, name="blocksize"),
    path("transactionsize/", main.transactionsize, name="transactionsize"),
    path("blockchainsize/", main.blockchainsize, name="blockchainsize"),
    path("difficulty/", main.difficulty, name="difficulty"),
    path("transmonth/", main.transmonth, name="transmonth"),
    path("deviation/", main.deviation, name="deviation"),
    path("deviation_tx/", main.deviation_tx, name="deviation_tx"),
    path(
        "transactiondominance/", main.transactiondominance, name="transactiondominance"
    ),
    path("percentmonth/", main.percentmonth, name="percentmonth"),
    path("securitybudget/", main.securitybudget, name="securitybudget"),
    path("efficiency/", main.efficiency, name="efficiency"),
    path("p2pool_hashrate/", main.p2pool_hashrate, name="p2pool_hashrate"),
    path("p2pool_dominance/", main.p2pool_dominance, name="p2pool_dominance"),
    path("p2pool_miners/", main.p2pool_miners, name="p2pool_miners"),
    path("p2pool_totalblocks/", main.p2pool_totalblocks, name="p2pool_totalblocks"),
    path(
        "metcalfesats_deviation/",
        main.metcalfesats_deviation,
        name="metcalfesats_deviation",
    ),
    path("metcalfe_deviation/", main.metcalfe_deviation, name="metcalfe_deviation"),
    path("marketcycle/", main.marketcycle, name="marketcycle"),
    path("shielded/", main.shielded, name="shielded"),
    path("pricesatslog/", main.pricesatslog, name="pricesatslog"),
    path("comptransactions/", main.comptransactions, name="comptransactions"),
    path("p2pool_totalhashes/", main.p2pool_totalhashes, name="p2pool_totalhashes"),
    path("miningprofitability/", main.miningprofitability, name="miningprofitability"),
    path("withdrawals/", main.withdrawals, name="withdrawals"),
    # URLs to useful functions on charts/main.py
    # Only admins can use these
    path(
        "get_history/<str:symbol>/<str:start_time>/<str:end_time>/",
        authenticated.get_history,
        name="get_history",
    ),
    path(
        "get_complete_history/<str:symbol>/",
        authenticated.get_history,
        name="get_complete_history",
    ),
    path("load_dominance/<str:symbol>/", authenticated.load_dominance, name="load_dominance"),
    path("load_rank/<str:symbol>/", authenticated.load_rank, name="load_rank"),
    path("load_p2pool/", authenticated.load_p2pool, name="load_p2pool"),
    path("populate_database/", authenticated.populate_database, name="populate_database"),
    path("importer/", authenticated.importer, name="importer"),
    path("reset/<str:symbol>/", authenticated.reset, name="reset"),
    path(
        "update/<str:date_from>/<str:date_to>/",
        authenticated.update_database_admin,
        name="update",
    ),
    path("add_coin/", authenticated.add_coin, name="add_coin"),
]
