from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [

    # Pages URLs
    # Everyone can use these
    path('', views.index, name='index'),
    path('pricelog/', views.pricelog, name='pricelog'),
    path('movingaverage/', views.movingaverage, name='movingaverage'),
    path('pricelin/', views.pricelin, name='pricelin'),
    path('powerlaw/', views.powerlaw, name='powerlaw'),
    path('fractal/', views.fractal, name='fractal'),
    path('golden/', views.golden, name='golden'),
    path('competitors/', views.competitors, name='competitors'),
    path('competitorslin/', views.competitorslin, name='competitorslin'),
    path('competitorssats/', views.competitorssats, name='competitorssats'),
    path('competitorssatslin/', views.competitorssatslin, name='competitorssatslin'),
    path('translin/', views.translin, name='translin'),
    path('translog/', views.translog, name='translog'),
    path('metcalfesats/', views.metcalfesats, name='metcalfesats'),
    path('metcalfeusd/', views.metcalfeusd, name='metcalfeusd'),
    path('inflation/', views.inflation, name='inflation'),
    path('coins/', views.coins, name='coins'),
    path('extracoins/', views.extracoins, name='extracoins'),
    path('sfmodel/', views.sfmodel, name='sfmodel'),
    path('sfmodellin/', views.sfmodellin, name='sfmodellin'),
    path('sfmodel/', views.sfmodel, name='sfmodel'),
    path('sfmultiple/', views.sfmultiple, name='sfmultiple'),
    path('about/', views.about, name='about'),
    path('compinflation/', views.compinflation, name='compinflation'),
    path('bitcoin/', views.bitcoin, name='bitcoin'),
    path('pt/', views.pt, name='pt'),
    path('fr/', views.fr, name='fr'),
    path('index_pt/', views.pt, name='index_pt'),
    path('thermocap/', views.thermocap, name='thermocap'),
    path('sharpe/', views.sharpe, name='sharpe'),
    path('pricesats/', views.pricesats, name='pricesats'),
    path('social/', views.social, name='social'),
    path('social2/', views.social2, name='social2'),
    path('social3/', views.social3, name='social3'),
    path('social4/', views.social4, name='social4'),
    path('social5/', views.social5, name='social5'),
    path('social6/', views.social6, name='social6'),
    path('social7/', views.social7, name='social7'),
    path('hashrate/', views.hashrate, name='hashrate'),
    path('hashprice/', views.hashprice, name='hashprice'),
    path('hashvsprice/', views.hashvsprice, name='hashvsprice'),
    path('inflationfractal/', views.inflationfractal, name='inflationfractal'),
    path('dailyemission/', views.dailyemission, name='dailyemission'),
    path('dailyemissionntv/', views.dailyemissionntv, name='dailyemissionntv'),
    path('transcost/', views.transcost, name='transcost'),
    path('transcostntv/', views.transcostntv, name='transcostntv'),
    path('minerrevcap/', views.minerrevcap, name='minerrevcap'),
    path('minerrev/', views.minerrev, name='minerrev'),
    path('minerrevntv/', views.minerrevntv, name='minerrevntv'),
    path('minerfees/', views.minerfees, name='minerfees'),
    path('minerfeesntv/', views.minerfeesntv, name='minerfeesntv'),
    path('commit/', views.commit, name='commit'),
    path('commitntv/', views.commitntv, name='commitntv'),
    path('inflationreturn/', views.inflationreturn, name='inflationreturn'),
    path('dread_subscribers/', views.dread_subscribers, name='dread_subscribers'),
    path('coincards/', views.coincards, name='coincards'),
    path('merchants/', views.merchants, name='merchants'),
    path('merchants_increase/', views.merchants_increase, name='merchants_increase'),
    path('merchants_percentage/', views.merchants_percentage, name='merchants_percentage'),
    path('dominance/', views.dominance, name='dominance'),
    path('rank/', views.rank, name='rank'),
    path('percentage/', views.percentage, name='percentage'),
    path('marketcap/', views.marketcap, name='marketcap'),
    path('tail_emission/', views.tail_emission, name='tail_emission'),
    path('privacymarketcap/', views.privacymarketcap, name='privacymarketcap'),
    path('privacydominance/', views.privacydominance, name='privacydominance'),
    path('monerodominance/', views.monerodominance, name='monerodominance'),
    path('blocksize/', views.blocksize, name='blocksize'),
    path('transactionsize/', views.transactionsize, name='transactionsize'),
    path('blockchainsize/', views.blockchainsize, name='blockchainsize'),
    path('difficulty/', views.difficulty, name='difficulty'),
    path('transmonth/', views.transmonth, name='transmonth'),
    path('deviation/', views.deviation, name='deviation'),
    path('deviation_tx/', views.deviation_tx, name='deviation_tx'),
    path('transactiondominance/', views.transactiondominance, name='transactiondominance'),
    path('percentmonth/', views.percentmonth, name='percentmonth'),
    path('pageviews/', views.pageviews, name='pageviews'),
    path('securitybudget/', views.securitybudget, name='securitybudget'),
    path('efficiency/', views.efficiency, name='efficiency'),
    path('p2pool_hashrate/', views.p2pool_hashrate, name='p2pool_hashrate'),
    path('p2pool_miners/', views.p2pool_miners, name='p2pool_miners'),
    path('p2pool_totalblocks/', views.p2pool_totalblocks, name='p2pool_totalblocks'),
    path('metcalfesats_deviation/', views.metcalfesats_deviation, name='metcalfesats_deviation'),
    path('metcalfe_deviation/', views.metcalfe_deviation, name='metcalfe_deviation'),

    # URLs to useful functions on charts/views.py
    # Only admins can use these 
    path('get_history/<str:symbol>/<str:start_time>/<str:end_time>/', views.get_history, name='get_history'),
    path('get_complete_history/<str:symbol>/', views.get_history, name='get_complete_history'),
    path('load_dominance/<str:symbol>/', views.load_dominance, name='load_dominance'),
    path('load_rank/<str:symbol>/', views.load_rank, name='load_rank'),
    path('load_p2pool/', views.load_p2pool, name='load_p2pool'),
    path('populate_database/', views.populate_database, name='populate_database'),
    path('importer/', views.importer, name='importer'),
    path('reset/<str:symbol>/', views.reset, name='reset'),
    path('update/<str:date_from>/<str:date_to>/', views.update_database_admin, name='update'),

    # URLs to old functions in case they need to be restablished
    # Everyone can use these, but they are hidden
    path('sfmodellin_old/', views.sfmodellin_old, name='sfmodellin_old'),
    path('sfmodel_old/', views.sfmodel_old, name='sfmodel_old'),
    path('dailyemission_old/', views.dailyemission_old, name='dailyemission_old'),
    path('dailyemissionntv_old/', views.dailyemissionntv_old, name='dailyemissionntv_old'),
    path('compinflation_old/', views.compinflation_old, name='compinflation_old'),
    path('bitcoin_old/', views.bitcoin_old, name='bitcoin_old'),
    path('inflation_old/', views.inflation_old, name='inflation_old'),
    path('coins_old/', views.coins_old, name='coins_old'),
    path('extracoins_old/', views.extracoins_old, name='extracoins_old'),
    path('transcost_old/', views.transcost_old, name='transcost_old'),
    path('transcostntv_old/', views.transcostntv_old, name='transcostntv_old'),
    path('metcalfesats_old/', views.metcalfesats_old, name='metcalfesats_old'),
    path('metcalfeusd_old/', views.metcalfeusd_old, name='metcalfeusd_old'),
    path('minerrev_old/', views.minerrev_old, name='minerrev_old'),
    path('minerrevntv_old/', views.minerrevntv_old, name='minerrevntv_old'),
    path('minerfees_old/', views.minerfees_old, name='minerfees_old'),
    path('minerfeesntv_old/', views.minerfeesntv_old, name='minerfeesntv_old'),
    path('commit_old/', views.commit_old, name='commit_old'),
    path('commitntv_old/', views.commitntv_old, name='commitntv_old'),
    path('percentage_old/', views.percentage_old, name='percentage_old'),
    path('marketcap_old/', views.marketcap_old, name='marketcap_old'),
    path('pricesats_old/', views.pricesats_old, name='pricesats_old'),
    path('social_old/', views.social_old, name='social_old'),
    path('social2_old/', views.social2_old, name='social2_old'),
    path('social3_old/', views.social3_old, name='social3_old'),
    path('social4_old/', views.social4_old, name='social4_old'),
    path('social5_old/', views.social5_old, name='social5_old'),
    path('social6_old/', views.social6_old, name='social6_old'),
    path('social7_old/', views.social7_old, name='social7_old'),
    
]