"""
Django settings for moneropro project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

## Default settings for a development environment, create a separate settings file for other environments

import os
from pathlib import Path

# Necessary for assynchronous django
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "rest.settings")
os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"

# Database on sepatare path than source code, so code can be treated as ephemeral
MONEROJ_REDIS_HOST = "redis:6379"
MONEROJ_SPREADSHEET_DIR = "/opt"
CSV_DATA_SHEET = "moneroj_data.ods"

SQLITE_FILEPATH = "/opt/db.sqlite3"

BASE_DIR = Path(__file__).resolve().parent.parent
CELERYD_CHDIR=BASE_DIR
CELERY_BIN="/usr/local/bin/celery"

SOCKS_PROXY_ENABLED = True
SOCKS_PROXY_HOST = "10.10.10.1"
SOCKS_PROXY_PORT = "1080"

TOR_HOST = "tor-socks"
TOR_PORT = "9050"

# Set REDDIT_CLIENT_SECRET as environment variable
REDDIT_REDIRECT_URI = "http://localhost:8000"

BITCOIN_EXPLORER_CACHE_DIR = "/tmp/bitcoin-explorer-api"

DEBUG = True
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATIC_URL = "/static/"
LOCALE_PATHS = (os.path.join(BASE_DIR, "locale/"),)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "django",
    ]

CORS_ALLOWED_ORIGINS = [f"http://{host}" for host in ALLOWED_HOSTS] + [
    f"https://{host}" for host in ALLOWED_HOSTS
]

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "charts",
    "tasks",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
]

ROOT_URLCONF = "moneropro.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "moneropro.wsgi.application"


# Database

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": SQLITE_FILEPATH,
    }
}

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_L10N = True
USE_TZ = True
